_wandb:
    value:
        cli_version: 0.27.0
        e:
            t1lt33dweyf6ls9f8gp6gqadxf2dvsgh:
                args:
                    - --data-dir
                    - datasets/IXI_unigrad_io
                    - --out-dir
                    - assets/runs/unigrad-io/error_unet_run2
                    - --epoch
                    - "50"
                    - --num-workers
                    - "4"
                    - --compile
                    - --wandb
                    - --wandb-project
                    - unc-quan
                    - --wandb-run-name
                    - unigradio_unet_run2
                codePath: experiments/regression/unigrad-io/train_unigrad_io_unet.py
                codePathLocal: experiments/regression/unigrad-io/train_unigrad_io_unet.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1885854916608"
                        used: "736408616960"
                email: shahikuber54@gmail.com
                executable: /files/venvs/unc/bin/python
                git:
                    commit: 96ca71da122d979e9c91c128064015785541e50c
                    remote: git@github.com:kubershahi/uncertainty-quantification.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-a077b1e0-2b89-662d-d447-6c9e7dff42e3
                host: unc-jupyter-7868c6565b-4kqqr
                memory:
                    total: "540888227840"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.35
                program: /files/repo/uncertainty-quantification/experiments/regression/unigrad-io/train_unigrad_io_unet.py
                python: CPython 3.11.9
                root: /files/repo/uncertainty-quantification/assets/runs/unigrad-io/error_unet_run2
                startedAt: "2026-05-18T02:16:30.678482Z"
                writerId: t1lt33dweyf6ls9f8gp6gqadxf2dvsgh
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.11.9
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
atlas_mask_file:
    value: atlas_valid_mask.npz
base_channels:
    value: 32
batch_size:
    value: 2
compile:
    value: true
data_dir:
    value: /files/repo/uncertainty-quantification/datasets/IXI_unigrad_io
device:
    value: cuda
early_stop_patience:
    value: 10
epochs:
    value: 50
image_norm:
    value: robust
in_channels:
    value: 5
inputs:
    value:
        - source
        - atlas
        - phi_pred
lr:
    value: 0.001
lr_factor:
    value: 0.5
lr_patience:
    value: 5
lr_scheduler:
    value: plateau
max_train_files:
    value: null
max_val_files:
    value: null
metrics_csv:
    value: metrics.csv
min_lr:
    value: 1e-06
model:
    value: UNet3D
num_workers:
    value: 4
optimizer:
    value: AdamW
out_channels:
    value: 1
phi_scale:
    value: 64
quantile_high:
    value: 0.99
show_progress:
    value: true
smooth_weight:
    value: 0.02
target:
    value: error_map
train_files:
    value: 403
train_split:
    value: Train
val_every:
    value: 3
val_files:
    value: 58
val_split:
    value: Val
wandb:
    value: true
wandb_project:
    value: unc-quan
weight_decay:
    value: 1e-05
